import { getDb } from "@/lib/db/client";
import { SectionHeading, GlassCard } from "@/components/ui/Glass";
import { DeployerLogsTable } from "./DeployerLogsTable";

export default function DeployerLogsPage() {
  const db = getDb();
  const systems = db.prepare(`SELECT * FROM ai_systems WHERE deployer_role_applies = 1 ORDER BY name`).all() as any[];
  const logs = db.prepare(`SELECT * FROM deployer_logs ORDER BY generated_at DESC`).all() as any[];

  const logsBySystem = new Map<string, any[]>();
  for (const l of logs) {
    if (!logsBySystem.has(l.system_id)) logsBySystem.set(l.system_id, []);
    logsBySystem.get(l.system_id)!.push(l);
  }

  const applicable = systems.filter((s) => s.classification_status === "high_risk");
  const notApplicable = systems.filter((s) => s.classification_status !== "high_risk");

  return (
    <div className="space-y-6">
      <SectionHeading
        title="Deployer Logs &amp; Retention"
        subtitle="Art. 26(6) — minimum 6-month retention. Deployers of high-risk AI systems must keep the logs automatically generated by that system, to the extent under their control, for a period appropriate to the system's intended purpose, and at least six months, unless other Union or national law sets a longer period. This is distinct from the Provider suite's Art. 18 ten-year technical-documentation retention."
      />

      <GlassCard className="border-sky-500/30 bg-sky-500/5">
        <p className="text-xs text-[var(--text-secondary)]">
          Each system&apos;s log-batch countdown is computed live from <code className="text-[10px]">retention_expires_at</code> — never hand-typed. A batch inside its 30-day approach window to the Art. 26(6) minimum-retention boundary is flagged amber; a batch safely far from the boundary (before or already past it) reads green.
        </p>
      </GlassCard>

      <div>
        <h3 className="font-heading font-semibold text-sm mb-3">Applicable — deployer role, high-risk (Art. 26(6) statutory minimum applies)</h3>
        <DeployerLogsTable systems={applicable} logsBySystem={Object.fromEntries(applicable.map((s) => [s.id, logsBySystem.get(s.id) ?? []]))} applicable />
      </div>

      {notApplicable.length > 0 && (
        <div>
          <h3 className="font-heading font-semibold text-sm mb-3 text-[var(--text-muted)]">Not applicable — informational log batches only (system not classified high-risk; Art. 26(6) statutory minimum-retention duty does not attach)</h3>
          <DeployerLogsTable systems={notApplicable} logsBySystem={Object.fromEntries(notApplicable.map((s) => [s.id, logsBySystem.get(s.id) ?? []]))} applicable={false} />
        </div>
      )}
    </div>
  );
}
